version: "3"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/nextjs-express-stack
      - ALLOW_CORS_CREDENTIALS=true
    ports:
      - 4000:4000
    volumes:
      - ./backend/src:/app/src

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.local
    environment:
      - NEXT_PUBLIC_BASE_API_URL=http://localhost:4000
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
